repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: check-merge-conflict
          - id: check-added-large-files
          - id: check-ast
          - id: check-symlinks
          - id: trailing-whitespace
          - id: check-json
          - id: debug-statements
          - id: pretty-format-json
            args: ["--autofix", "--allow-missing-credentials"]
    - repo: https://github.com/PyCQA/isort
      rev: 5.10.1
      hooks:
          - id: isort
            args: ["--profile", "black"]
    - repo: https://github.com/PyCQA/flake8
      rev: 4.0.1
      hooks:
          - id: flake8
            additional_dependencies: [flake8-print]
            files: '\.py$'
            exclude: docs/
            args:
                - --select=F403,F406,F821,T003
    - repo: https://github.com/humitos/mirrors-autoflake
      rev: v1.3
      hooks:
          - id: autoflake
            files: '\.py$'
            exclude: '^\..*'
            args: ["--in-place"]
    - repo: https://github.com/psf/black
      rev: 22.3.0
      hooks:
          - id: black
            args: ["--target-version", "py38"]
    - repo: https://github.com/asottile/pyupgrade
      rev: v2.34.0
      hooks:
          - id: pyupgrade
            args: [--py37-plus]
    - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
      rev: "v8.0.0"
      hooks:
          - id: commitlint
            stages: [commit-msg]
            additional_dependencies: ['@commitlint/config-conventional']
    - repo: https://github.com/DavidAnson/markdownlint-cli2
      rev: "v0.4.0"
      hooks:
          - id: markdownlint-cli2
            name: markdownlint-cli2
            exclude: docs/
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: "v2.6.2"
      hooks:
          - id: prettier
            args: [--prose-wrap, always]
            types: [markdown]
            exclude: docs/index.md
