[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "asgi_aws"
dist-name = "asgi_aws"
author = "Yasser Tahiri"
author-email = "hello@yezz.me"
home-page = "https://github.com/yezz123/asgi-aws"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Framework :: AsyncIO",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Internet :: WWW/HTTP :: Session",
    "Typing :: Typed",
]
description-file = "README.md"
requires-python = ">=3.8"
requires = [
    "typing-extensions >=3.7.4, <4.0.0"
]

[tool.flit.metadata.requires-extra]
lint = [
    "pre-commit==2.19.0",
    "mypy==0.931",
]
test = [
    "pytest==7.1.2",
    "pytest-asyncio == 0.18.3",
    "codecov==2.1.12",
    "pytest-cov==3.0.0",
    "fastapi >=0.65.2,<0.78.0",
    "pydantic==1.9.1",
    "python-multipart"
]